package Views;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import Controllers.AccountController;
import Controllers.AccountRoleController;
import Controllers.ContactController;
import Controllers.FamilyInfoController;
import Controllers.StudentController;
import Models.DatabaseModel;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.Color;
import javax.swing.JTextField;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class FormMainView extends javax.swing.JFrame {

	public FormMainView() {
		initComponents();
		DatabaseModel databaseModel = new DatabaseModel();

		List<Object[]> result = databaseModel.accountShowAllRecord();

		String arrayHeader[] = { "accountID", "userName", "password", "createOn", "lastLogin", "accountID", "roleID",
				"grantDate", "roleID", "roleName", "TC" };
		DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);
		for (Object[] accounts : result) {
			table.addRow(accounts);
		}
		tblAccountList.setModel(table);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jPanel8 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		btnAccountAdd = new javax.swing.JButton();
		lblogrencipanel = new javax.swing.JLabel();
		btnAccountUpdate = new javax.swing.JButton();
		btnAccountRefresh = new javax.swing.JButton();
		btnAccountDelete = new javax.swing.JButton();
		btnAccountClear = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		txttc = new javax.swing.JTextField();
		lbltc = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		lblFistName = new javax.swing.JLabel();
		lblLastName = new javax.swing.JLabel();
		lblAge = new javax.swing.JLabel();
		lblGender = new javax.swing.JLabel();
		txtFirstName = new javax.swing.JTextField();
		txtLastName = new javax.swing.JTextField();
		txtAge = new javax.swing.JTextField();
		cmbGender = new javax.swing.JComboBox<>();
		lblPersonalInfo = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		lblFamilyInfo = new javax.swing.JLabel();
		lblMotherName = new javax.swing.JLabel();
		lblFatherName = new javax.swing.JLabel();
		lblMotherJob = new javax.swing.JLabel();
		lblFatherJob = new javax.swing.JLabel();
		txtMotherName = new javax.swing.JTextField();
		txtFatherName = new javax.swing.JTextField();
		txtMotherJob = new javax.swing.JTextField();
		txtFatherJob = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		lblPhone = new javax.swing.JLabel();
		lblAddress = new javax.swing.JLabel();
		lblMail = new javax.swing.JLabel();
		txtPhone = new javax.swing.JTextField();
		txtAddress = new javax.swing.JTextField();
		txtMail = new javax.swing.JTextField();
		jPanel6 = new javax.swing.JPanel();
		jScrollPaneAccountList = new javax.swing.JScrollPane();
		tblAccountList = new javax.swing.JTable();
		lblAccountList = new javax.swing.JLabel();
		lblError = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setAutoRequestFocus(false);
		setBackground(new java.awt.Color(255, 65, 63));
		setForeground(java.awt.Color.darkGray);

		lblogrencipanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		lblogrencipanel.setText("ACCOUNT RECORD PANEL");

		btnAccountAdd.setBackground(java.awt.Color.pink);
		btnAccountAdd.setText("ADD");
		btnAccountAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAccountAddActionPerformed(evt);
			}
		});

		btnAccountUpdate.setBackground(java.awt.Color.pink);
		btnAccountUpdate.setText("UPDATE");
		btnAccountUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAccountUpdateActionPerformed(evt);
			}
		});

		btnAccountRefresh.setBackground(java.awt.Color.pink);
		btnAccountRefresh.setText("REFRESH");
		btnAccountRefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAccountRefreshActionPerformed(evt);
			}
		});

		btnAccountDelete.setBackground(java.awt.Color.pink);
		btnAccountDelete.setText("DELETE");
		btnAccountDelete.setActionCommand("");
		btnAccountDelete.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				btnAccountDeleteActionPerformed(evt);
			}
		});

		btnAccountClear.setBackground(java.awt.Color.pink);
		btnAccountClear.setText("CLEAR");
		btnAccountClear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAccountClearActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnAccountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)
						.addComponent(btnAccountUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnAccountDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnAccountRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnAccountClear, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(144, 144, 144))
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(195, 195, 195).addComponent(lblogrencipanel)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap(36, Short.MAX_VALUE)
						.addComponent(lblogrencipanel).addGap(18, 18, 18)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnAccountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAccountUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAccountRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAccountDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnAccountClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(27, 27, 27)));

		jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
				java.awt.Color.darkGray, null));

		txttc.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				txttcKeyPressed(evt);
			}
		});

		lbltc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
		lbltc.setForeground(new java.awt.Color(204, 0, 0));
		lbltc.setText("TC");

		JLabel lblUserName = new JLabel();
		lblUserName.setText("User Name");
		lblUserName.setForeground(new Color(204, 0, 0));
		lblUserName.setFont(new Font("Dialog", Font.BOLD, 12));

		txtUserName = new JTextField();

		JLabel lblPassword = new JLabel();
		lblPassword.setText("Password");
		lblPassword.setForeground(new Color(204, 0, 0));
		lblPassword.setFont(new Font("Dialog", Font.BOLD, 12));

		txtPassword = new JTextField();

		txtRePassword = new JTextField();

		lblRePassword = new JLabel();
		lblRePassword.setText("Re-Password");
		lblRePassword.setForeground(new Color(204, 0, 0));
		lblRePassword.setFont(new Font("Dialog", Font.BOLD, 12));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel7Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addComponent(lbltc, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(txttc, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel7Layout.createSequentialGroup()
								.addComponent(lblUserName, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(txtUserName, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel7Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel7Layout.createSequentialGroup()
										.addComponent(lblRePassword, GroupLayout.PREFERRED_SIZE, 93,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(txtRePassword, GroupLayout.PREFERRED_SIZE, 187,
												GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel7Layout.createSequentialGroup()
										.addComponent(lblPassword, GroupLayout.PREFERRED_SIZE, 93,
												GroupLayout.PREFERRED_SIZE)
										.addGap(18).addComponent(txtPassword, GroupLayout.PREFERRED_SIZE, 187,
												GroupLayout.PREFERRED_SIZE))))
				.addContainerGap(50, Short.MAX_VALUE)));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel7Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lbltc, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(txttc, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblUserName, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtUserName, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
						.addGap(9)
						.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(lblPassword, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtPassword, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(lblRePassword, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtRePassword, GroupLayout.PREFERRED_SIZE, 26,
										GroupLayout.PREFERRED_SIZE))
						.addContainerGap(41, Short.MAX_VALUE)));
		jPanel7.setLayout(jPanel7Layout);

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
				java.awt.Color.darkGray, null));

		lblFistName.setText("First Name");

		lblLastName.setText("Last Name");

		lblAge.setText("Age");

		lblGender.setText("Gender");

		cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "WOMAN", "MAN" }));

		lblPersonalInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		lblPersonalInfo.setText("Personal Info");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblPersonalInfo).addGap(112, 112, 112))
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(lblFistName, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 185,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(cmbGender, javax.swing.GroupLayout.Alignment.LEADING, 0,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addContainerGap(27, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap(19, Short.MAX_VALUE)
						.addComponent(lblPersonalInfo).addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblFistName, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblAge).addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(64, 64, 64)));

		lblAge.getAccessibleContext().setAccessibleName("YAŞ");

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
				java.awt.Color.darkGray, null));

		lblFamilyInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		lblFamilyInfo.setText("Family Info");

		lblMotherName.setText("Mother Name");

		lblFatherName.setText("Father Name");

		lblMotherJob.setText("Mother Job");

		lblFatherJob.setText("Father Job");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(22, 22, 22).addComponent(
												lblFatherJob, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
												javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20).addComponent(
												lblMotherJob, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(txtFatherJob, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtMotherJob, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(lblFatherName, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lblMotherName, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 190,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(26, 26, 26))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(lblFamilyInfo,
								javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(95, 95, 95)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20).addComponent(lblFamilyInfo)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblMotherJob, javax.swing.GroupLayout.PREFERRED_SIZE, 21,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMotherJob, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblFatherJob, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtFatherJob, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(40, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
				java.awt.Color.darkGray, null));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("Contact Info");

		lblPhone.setText("Phone");

		lblAddress.setText("Address");

		lblMail.setText("Mail");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblAddress).addComponent(lblPhone))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 181,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 181,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 181,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, 118,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(29, 29, 29)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblPhone))
						.addGap(18, 18, 18)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblAddress).addComponent(txtAddress,
										javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(14, 14, 14)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblMail).addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(83, 83, 83)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(49, 49, 49)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addContainerGap()));

		tblAccountList.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { 
						{ null, null, null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null, null, null } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8",
						"Title 9", "Title 10", "Title 11", "Title 12", "Title 13" }));
		jScrollPaneAccountList.setViewportView(tblAccountList);

		lblAccountList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		lblAccountList.setText("Account List");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6Layout.setHorizontalGroup(
			jPanel6Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel6Layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(lblAccountList)
					.addGap(1001))
				.addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jScrollPaneAccountList, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(57, Short.MAX_VALUE))
		);
		jPanel6Layout.setVerticalGroup(
			jPanel6Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblAccountList)
					.addGap(26)
					.addComponent(jScrollPaneAccountList, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(45, Short.MAX_VALUE))
		);
		jPanel6.setLayout(jPanel6Layout);

		lblError.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		lblError.setForeground(java.awt.Color.red);

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel8Layout
				.createSequentialGroup().addGap(55)
				.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 337, GroupLayout.PREFERRED_SIZE)
								.addGap(121)
								.addComponent(lblError, GroupLayout.PREFERRED_SIZE, 504, GroupLayout.PREFERRED_SIZE))
						.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
				.addContainerGap(75, Short.MAX_VALUE))
				.addGroup(jPanel8Layout.createSequentialGroup().addContainerGap(401, Short.MAX_VALUE)
						.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 658, GroupLayout.PREFERRED_SIZE)
						.addGap(317)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel8Layout
				.createSequentialGroup()
				.addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(68)
								.addComponent(lblError, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
								.addGap(13))
						.addGroup(jPanel8Layout.createSequentialGroup()
								.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)))
				.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.RELATED)
				.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGap(120)));
		jPanel8.setLayout(jPanel8Layout);

		jScrollPane2.setViewportView(jPanel8);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 27, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(29, Short.MAX_VALUE).addComponent(jScrollPane2,
						javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(28, 28, 28)));

		pack();
	}

	private void btnAccountAddActionPerformed(java.awt.event.ActionEvent evt) {

		DatabaseModel databaseModel = new DatabaseModel();
		java.sql.Date sqlDate = new java.sql.Date(new java.util.Date().getTime());

		AccountController accountController = new AccountController();
		accountController.setUserName(txtUserName.getText());
		if (txtPassword.getText().equals(txtRePassword.getText())) {
			accountController.setPassword(txtPassword.getText());
		} else {
			lblError.setText("Passwor not equal");
		}
		accountController.setCreatedOn(sqlDate);
		accountController.setLastLogin(sqlDate);
		accountController.setTc(Integer.parseInt(txttc.getText()));

		AccountRoleController accountRoleController = new AccountRoleController();
		accountRoleController.setRoleID(3);
		accountRoleController.setGrantDate(sqlDate);

		StudentController studentController = new StudentController();
		studentController.setFirstName(txtFirstName.getText());
		studentController.setLastName(txtLastName.getText());
		studentController.setTC(Integer.parseInt(txttc.getText()));
		studentController.setAge(Short.parseShort(txtAge.getText()));
		studentController.setGender(cmbGender.toString().charAt(0));

		FamilyInfoController familyInfoController = new FamilyInfoController();
		familyInfoController.setMotherName(txtMotherName.getText());
		familyInfoController.setMotherJob(txtMotherJob.getText());
		familyInfoController.setFatherName(txtFatherName.getText());
		familyInfoController.setFatherJob(txtFatherJob.getText());

		ContactController contactController = new ContactController();
		contactController.setPhoneNumber(txtPhone.getText());
		contactController.setMail(txtMail.getText());
		contactController.setAddress(txtAddress.getText());

		databaseModel.accountRecord(accountController, accountRoleController, studentController, familyInfoController,
				contactController);

		if (txttc != null) {
			lblError.setText("      kişi eklendi !!!");

		}
		lblError.setText(" ");

	}

	private void btnAccountUpdateActionPerformed(java.awt.event.ActionEvent evt) {

		lblError.setText("     veri güncellendi ");
		lblError.setText(" ");

	}

	private void btnAccountRefreshActionPerformed(java.awt.event.ActionEvent evt) {

		DatabaseModel databaseModel = new DatabaseModel();

		List<Object[]> result = databaseModel.accountShowAllRecord();

		String arrayHeader[] = { "accountID", "userName", "password", "createOn", "lastLogin", "accountID", "roleID",
				"grantDate", "roleID", "roleName", "tc" };
		DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);
		for (Object[] accounts : result) {
			table.addRow(accounts);
		}
		tblAccountList.setModel(table);
	}

	private void btnAccountDeleteActionPerformed(java.awt.event.ActionEvent evt) {

		DatabaseModel databaseModel = new DatabaseModel();
		
		databaseModel.accountDelete(Integer.parseInt(txttc.getText()));
		
		if(txttc != null) {
			lblError.setText(txttc.getText() + " tc number account deleted.");
		}
	}

	private void btnAccountClearActionPerformed(java.awt.event.ActionEvent evt) {
		
		txttc.setText(" ");
		txtUserName.setText(" ");
		txtPassword.setText(" ");
		txtRePassword.setText(" ");
		
		txtFirstName.setText(" ");
		txtLastName.setText(" ");
		txtAge.setText(" ");
		txtMotherName.setText(" ");
		txtFatherName.setText(" ");
		txtMotherJob.setText(" ");
		txtFatherJob.setText(" ");
		txtPhone.setText(" ");
		txtAddress.setText(" ");
		txtMail.setText(" ");
		lblError.setText(" ");

	}

	private void txttcKeyPressed(java.awt.event.KeyEvent evt) {
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

			DatabaseModel databaseModel = new DatabaseModel();
			AccountController accountController = new AccountController();

			accountController = databaseModel.accountFind(Integer.parseInt(txttc.getText()));

			if (accountController.getStudentController().getTC() == 0) {
				lblError.setText(txttc.getText() + " not found tc");
			} else {
				lblError.setText(" ");

				txtUserName.setText(accountController.getUserName());
				txtPassword.setText(accountController.getPassword());

				txtFirstName.setText(accountController.getStudentController().getFirstName());
				txtLastName.setText(accountController.getStudentController().getLastName());
				txtAge.setText(String.valueOf(accountController.getStudentController().getAge()));
				cmbGender.setSelectedItem(accountController.getStudentController().getGender());

				txtMotherName.setText(accountController.getFamilyInfoController().getMotherName());
				txtFatherName.setText(accountController.getFamilyInfoController().getFatherName());
				txtMotherJob.setText(accountController.getFamilyInfoController().getMotherJob());
				txtFatherJob.setText(accountController.getFamilyInfoController().getFatherJob());

				txtPhone.setText(accountController.getContactController().getPhoneNumber());
				txtAddress.setText(accountController.getContactController().getAddress());
				txtMail.setText(accountController.getContactController().getMail());
				lblError.setText(" ");
			}

		}
	}

	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormMainView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormMainView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormMainView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormMainView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormMainView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAccountUpdate;
	private javax.swing.JButton btnAccountAdd;
	private javax.swing.JButton btnAccountDelete;
	private javax.swing.JButton btnAccountClear;
	private javax.swing.JButton btnAccountRefresh;
	private javax.swing.JComboBox<String> cmbGender;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel lblAccountList;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JScrollPane jScrollPaneAccountList;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lblError;
	private javax.swing.JLabel lblFistName;
	private javax.swing.JLabel lblAddress;
	private javax.swing.JLabel lblFamilyInfo;
	private javax.swing.JLabel lblMotherName;
	private javax.swing.JLabel lblMotherJob;
	private javax.swing.JLabel lblFatherName;
	private javax.swing.JLabel lblFatherJob;
	private javax.swing.JLabel lblGender;
	private javax.swing.JLabel lblPersonalInfo;
	private javax.swing.JLabel lblMail;
	private javax.swing.JLabel lblogrencipanel;
	private javax.swing.JLabel lblLastName;
	private javax.swing.JLabel lbltc;
	private javax.swing.JLabel lblPhone;
	private javax.swing.JLabel lblAge;
	private javax.swing.JTable tblAccountList;
	private javax.swing.JTextField txtFirstName;
	private javax.swing.JTextField txtAddress;
	private javax.swing.JTextField txtMotherName;
	private javax.swing.JTextField txtMotherJob;
	private javax.swing.JTextField txtFatherName;
	private javax.swing.JTextField txtFatherJob;
	private javax.swing.JTextField txtMail;
	private javax.swing.JTextField txtLastName;
	private javax.swing.JTextField txttc;
	private javax.swing.JTextField txtPhone;
	private javax.swing.JTextField txtAge;
	private JTextField txtUserName;
	private JTextField txtPassword;
	private JTextField txtRePassword;
	private JLabel lblRePassword;
}