/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * 
 */
public class JFrameMainInstructor extends javax.swing.JFrame {

    JIntFrmAddPoints jIntFrmAddPoints;
    public int account_id;
    
    /**
     * Creates new form JFrameMainInstructor
     */
    public JFrameMainInstructor() {
        initComponents();
        this.setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnAddPoints = new javax.swing.JMenuItem();
        jMnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMnAddPoints.setText("Add Points");
        jMnAddPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAddPointsActionPerformed(evt);
            }
        });
        jMenu1.add(jMnAddPoints);

        jMnExit.setText("Exit");
        jMnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnExitActionPerformed

    private void jMnAddPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAddPointsActionPerformed
        if (jIntFrmAddPoints == null || jIntFrmAddPoints.isClosed()) {
            jIntFrmAddPoints = new JIntFrmAddPoints();
            jDesktopPane1.add(jIntFrmAddPoints);
            jIntFrmAddPoints.setVisible(true);
            
        } else {
            jIntFrmAddPoints.setLocation(this.getWidth() / 2 - jIntFrmAddPoints.getWidth() / 2,
                    this.getHeight() / 2 - jIntFrmAddPoints.getHeight() / 2);
            jIntFrmAddPoints.setVisible(true);
        }
    }//GEN-LAST:event_jMnAddPointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMainInstructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnAddPoints;
    private javax.swing.JMenuItem jMnExit;
    // End of variables declaration//GEN-END:variables
}
