/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * 
 */
public class JFrameMainStudent extends javax.swing.JFrame {

    JIntFrmAddCoursesOfStudent jIntFrmAddCoursesOfStudent;
    public int account_id;
    /**
     * Creates new form JFrameMainStudent
     */
    public JFrameMainStudent() {
        initComponents();
        this.setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnAddCourses = new javax.swing.JMenuItem();
        jMnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(67, 163, 236));
        getContentPane().add(jDesktopPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMnAddCourses.setText("Add Courses");
        jMnAddCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnAddCoursesActionPerformed(evt);
            }
        });
        jMenu1.add(jMnAddCourses);

        jMnExit.setText("Exit");
        jMnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reports");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnExitActionPerformed

    private void jMnAddCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnAddCoursesActionPerformed
        if (jIntFrmAddCoursesOfStudent == null || jIntFrmAddCoursesOfStudent.isClosed()) {
            jIntFrmAddCoursesOfStudent = new JIntFrmAddCoursesOfStudent();
            jDesktopPane.add(jIntFrmAddCoursesOfStudent);
            jIntFrmAddCoursesOfStudent.setVisible(true);
            jIntFrmAddCoursesOfStudent.setTitle("Account ID :" + this.getTitle());
            
        } else {
            jIntFrmAddCoursesOfStudent.setLocation(this.getWidth() / 2 - jIntFrmAddCoursesOfStudent.getWidth() / 2,
                    this.getHeight() / 2 - jIntFrmAddCoursesOfStudent.getHeight() / 2);
            jIntFrmAddCoursesOfStudent.setVisible(true);
        }
    }//GEN-LAST:event_jMnAddCoursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMainStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnAddCourses;
    private javax.swing.JMenuItem jMnExit;
    // End of variables declaration//GEN-END:variables
}
