/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.AccountController;
import Models.DatabaseModel;
import Views.JFrameMain;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gurkay
 */
public class JInternalFrameAccountList extends javax.swing.JInternalFrame {

    //private JFrameMain jFrameMain = new JFrameMain();
    /**
     * Creates new form JInternalFrameAccountList
     */
    public JInternalFrameAccountList() {
        initComponents();
        showAccount();
    }

    /**
     * To show all users data info
     */
    public void showAccount() {

        DatabaseModel databaseModel = new DatabaseModel();

        List<Object[]> result = databaseModel.accountShowAllRecord();

        String arrayHeader[] = {"Account ID", "TC", "User Name", "First Name", "Last Name", "Status"};
        DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);
        for (Object[] accounts : result) {
            table.addRow(accounts);
        }
        tblAccountList.setModel(table);
        jScrollPaneAccountList.setViewportView(tblAccountList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPersonalInfo = new javax.swing.JPanel();
        lblTc = new javax.swing.JLabel();
        txtTc = new javax.swing.JTextField();
        jScrollPaneAccountList = new javax.swing.JScrollPane();
        tblAccountList = new javax.swing.JTable();

        setClosable(true);
        setTitle("Account List");

        pnlPersonalInfo.setBackground(new java.awt.Color(222, 171, 123));

        lblTc.setText("TC");

        txtTc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTcKeyReleased(evt);
            }
        });

        jScrollPaneAccountList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPaneAccountListMouseReleased(evt);
            }
        });

        tblAccountList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccountList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountListMouseClicked(evt);
            }
        });
        jScrollPaneAccountList.setViewportView(tblAccountList);

        javax.swing.GroupLayout pnlPersonalInfoLayout = new javax.swing.GroupLayout(pnlPersonalInfo);
        pnlPersonalInfo.setLayout(pnlPersonalInfoLayout);
        pnlPersonalInfoLayout.setHorizontalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAccountList, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblTc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPersonalInfoLayout.setVerticalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTc)
                    .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneAccountList, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTcKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTcKeyPressed

    private void txtTcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTcKeyReleased
        // TODO add your handling code here:
        String query = txtTc.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txtTcKeyReleased

    private void tblAccountListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAccountListMouseClicked

    private void jScrollPaneAccountListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPaneAccountListMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPaneAccountListMouseReleased

    /**
     * To Filter Table Row data info
     */
    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>((DefaultTableModel) tblAccountList.getModel());
        tblAccountList.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneAccountList;
    private javax.swing.JLabel lblTc;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JTable tblAccountList;
    private javax.swing.JTextField txtTc;
    // End of variables declaration//GEN-END:variables
}
