/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.AccountController;
import Controllers.AddCourseStudentController;
import Controllers.GlobalConstants;
import Models.AddCourseStudentModel;
import Models.DatabaseModel;
import Models.InstructionOfCourseDbModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gurkay
 */
public class JIntFrmAddPoints extends javax.swing.JInternalFrame {

    DatabaseModel databaseModel = new DatabaseModel();
    AccountController accountController = new AccountController();
    InstructionOfCourseDbModel instructionOfCourseDbModel = new InstructionOfCourseDbModel();
    AddCourseStudentController addCourseStudentController = new AddCourseStudentController();
    AddCourseStudentModel addCourseStudentModel = new AddCourseStudentModel();

    /**
     * Creates new form JIntFrmAddPoints
     */
    public JIntFrmAddPoints() {
        initComponents();
        showInstructorOfCourses(GlobalConstants.globalConst_account_id);
    }

    /**
     * Show All Instructor Of Courses
     */
    public void showInstructorOfCourses(int accountID) {
        try {

            List<Object[]> result = instructionOfCourseDbModel.instOfCoursesFindRecord(accountID);

            String arrayHeader[] = {"IOCID", "Courses Name", "Courses Credit", "Courses Code"};
            DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);
            for (Object[] courses : result) {
                table.addRow(courses);
            }

            tblInstCoursesList.setModel(table);

            jScrollPaneInstCoursesList.setViewportView(tblInstCoursesList);

            accountController = databaseModel.accountIDFind(GlobalConstants.globalConst_account_id);

            lblAccountID.setText(String.valueOf(accountController.getAccountId()));
            txtInstructorTc.setText(accountController.getTc());
            txtInstructorFirstName.setText(accountController.getFirstName());
            txtInstructorLastName.setText(accountController.getLastName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getStackTrace());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRecordButtonSet = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneInstCoursesList = new javax.swing.JScrollPane();
        tblInstCoursesList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblAccountID = new javax.swing.JLabel();
        lblInstructorTc = new javax.swing.JLabel();
        lblInstructorFirstName = new javax.swing.JLabel();
        lblInstructorLastName = new javax.swing.JLabel();
        txtInstructorTc = new javax.swing.JTextField();
        txtInstructorFirstName = new javax.swing.JTextField();
        txtInstructorLastName = new javax.swing.JTextField();
        jlable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneInstructorOfCoursesList = new javax.swing.JScrollPane();
        tblInstructorOfCoursesList = new javax.swing.JTable();

        setClosable(true);

        pnlRecordButtonSet.setBackground(new java.awt.Color(244, 130, 17));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRecordButtonSetLayout = new javax.swing.GroupLayout(pnlRecordButtonSet);
        pnlRecordButtonSet.setLayout(pnlRecordButtonSetLayout);
        pnlRecordButtonSetLayout.setHorizontalGroup(
            pnlRecordButtonSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordButtonSetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRecordButtonSetLayout.setVerticalGroup(
            pnlRecordButtonSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordButtonSetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(225, 141, 57));

        jScrollPaneInstCoursesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPaneInstCoursesListMouseClicked(evt);
            }
        });

        tblInstCoursesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IOCID", "Courses Name", "Courses Credit", "Curses Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInstCoursesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInstCoursesListMouseClicked(evt);
            }
        });
        jScrollPaneInstCoursesList.setViewportView(tblInstCoursesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneInstCoursesList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneInstCoursesList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(225, 141, 57));

        lblAccountID.setText("Account ID");

        lblInstructorTc.setText("TC");

        lblInstructorFirstName.setText("Instructor First Name");

        lblInstructorLastName.setText("Instructor Last Name");

        txtInstructorTc.setEditable(false);

        txtInstructorFirstName.setEditable(false);

        txtInstructorLastName.setEditable(false);

        jlable.setText("Account ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInstructorTc)
                    .addComponent(lblInstructorFirstName)
                    .addComponent(lblInstructorLastName)
                    .addComponent(jlable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccountID)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtInstructorFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(txtInstructorTc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtInstructorLastName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountID)
                    .addComponent(jlable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtInstructorTc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInstructorFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblInstructorTc)
                        .addGap(12, 12, 12)
                        .addComponent(lblInstructorFirstName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtInstructorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblInstructorLastName)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(225, 141, 57));

        jScrollPaneInstructorOfCoursesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPaneInstructorOfCoursesListMouseClicked(evt);
            }
        });

        tblInstructorOfCoursesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInstructorOfCoursesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInstructorOfCoursesListMouseClicked(evt);
            }
        });
        jScrollPaneInstructorOfCoursesList.setViewportView(tblInstructorOfCoursesList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneInstructorOfCoursesList, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneInstructorOfCoursesList, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlRecordButtonSet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRecordButtonSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (Integer.parseInt(lblAccountID.getText()) > 0) {

            DefaultTableModel model = (DefaultTableModel) tblInstructorOfCoursesList.getModel();

            for (int count = 0; count < model.getRowCount(); count++) {
                
                addCourseStudentController.setAddCourseStudentId(Integer.parseInt(model.getValueAt(count, 0).toString()));
                addCourseStudentController.setMidterm(Float.parseFloat(model.getValueAt(count, 7).toString()));
                addCourseStudentController.setFinalExam(Float.parseFloat(model.getValueAt(count, 8).toString()));                
               
                addCourseStudentModel.updateCourseStudentPointRecord(addCourseStudentController);
            }
            
            JOptionPane.showMessageDialog(null, "Points Saved");
        }
                
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblInstCoursesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInstCoursesListMouseClicked
        try {

            int selectedRow = tblInstCoursesList.getSelectedRow();
            DefaultTableModel modelCourse = (DefaultTableModel) tblInstCoursesList.getModel();

            int cC = Integer.parseInt(modelCourse.getValueAt(selectedRow, 0).toString());
            List<Object[]> result = addCourseStudentModel.coursesOfStudentListSelected(cC);

            String arrayHeader[] = {"add_course_student_id", "account_id", "first_name", "last_name", "courses_code", "courses_name", "courses_credit", "midterm", "final"};
            DefaultTableModel table = new DefaultTableModel(arrayHeader, 0);
            for (Object[] courses : result) {
                table.addRow(courses);

            }

            tblInstructorOfCoursesList.setModel(table);
            jScrollPaneInstructorOfCoursesList.setViewportView(tblInstructorOfCoursesList);

        } catch (Exception e) {
            System.err.println(e.getStackTrace());
        }
    }//GEN-LAST:event_tblInstCoursesListMouseClicked

    private void tblInstructorOfCoursesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInstructorOfCoursesListMouseClicked

    }//GEN-LAST:event_tblInstructorOfCoursesListMouseClicked

    private void jScrollPaneInstructorOfCoursesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPaneInstructorOfCoursesListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPaneInstructorOfCoursesListMouseClicked

    private void jScrollPaneInstCoursesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPaneInstCoursesListMouseClicked

    }//GEN-LAST:event_jScrollPaneInstCoursesListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPaneInstCoursesList;
    private javax.swing.JScrollPane jScrollPaneInstructorOfCoursesList;
    private javax.swing.JLabel jlable;
    private javax.swing.JLabel lblAccountID;
    private javax.swing.JLabel lblInstructorFirstName;
    private javax.swing.JLabel lblInstructorLastName;
    private javax.swing.JLabel lblInstructorTc;
    private javax.swing.JPanel pnlRecordButtonSet;
    private javax.swing.JTable tblInstCoursesList;
    private javax.swing.JTable tblInstructorOfCoursesList;
    public javax.swing.JTextField txtInstructorFirstName;
    public javax.swing.JTextField txtInstructorLastName;
    public javax.swing.JTextField txtInstructorTc;
    // End of variables declaration//GEN-END:variables
}
